// <auto-generated />
using System;
using MessDotCity.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MessDotCity.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200725050319_UnreadNoticesAdded")]
    partial class UnreadNoticesAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MessDotCity.API.Models.DailyExpense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Day");

                    b.Property<float>("Expense");

                    b.Property<int>("MessId");

                    b.Property<string>("ResponsibleMember");

                    b.Property<float>("TotalMeal");

                    b.HasKey("Id");

                    b.ToTable("DailyExpenses");
                });

            modelBuilder.Entity("MessDotCity.API.Models.Deposit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("Credit");

                    b.Property<float>("Debit");

                    b.Property<DateTime>("EffectiveDate");

                    b.Property<int>("MemberId");

                    b.Property<int>("MessId");

                    b.Property<string>("Remarks");

                    b.HasKey("Id");

                    b.ToTable("Deposits");
                });

            modelBuilder.Entity("MessDotCity.API.Models.FixedExpense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("Amount");

                    b.Property<DateTime>("EffectiveDate");

                    b.Property<DateTime>("LastModifiedOn");

                    b.Property<int>("MessId");

                    b.Property<string>("Remarks");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("FixedExpenses");
                });

            modelBuilder.Entity("MessDotCity.API.Models.Meal", b =>
                {
                    b.Property<int>("MemberId");

                    b.Property<DateTime>("Day");

                    b.Property<float>("BreakFast");

                    b.Property<float>("Dinner");

                    b.Property<float>("Lunch");

                    b.Property<int?>("MessId");

                    b.HasKey("MemberId", "Day");

                    b.ToTable("Meals");
                });

            modelBuilder.Entity("MessDotCity.API.Models.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("DBreakfast");

                    b.Property<float>("DDinner");

                    b.Property<float>("DLunch");

                    b.Property<string>("FirstName");

                    b.Property<DateTime>("LastModifiedOn");

                    b.Property<string>("LastName");

                    b.Property<int>("MessId");

                    b.Property<string>("MessRole");

                    b.Property<string>("Mobile");

                    b.Property<string>("PhotoName");

                    b.Property<string>("Profession");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("MessDotCity.API.Models.MessInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOn");

                    b.Property<DateTime>("LastModifiedOn");

                    b.Property<string>("Location");

                    b.Property<DateTime>("MealChangeFrom");

                    b.Property<DateTime>("MealChangeTo");

                    b.Property<string>("MessName");

                    b.Property<string>("OwnerId");

                    b.Property<string>("SecretCode");

                    b.HasKey("Id");

                    b.ToTable("Messes");
                });

            modelBuilder.Entity("MessDotCity.API.Models.Notice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate");

                    b.Property<string>("Details");

                    b.Property<int>("MessId");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Notices");
                });

            modelBuilder.Entity("MessDotCity.API.Models.Request", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MessId");

                    b.Property<DateTime>("RequestedOn");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("MessDotCity.API.Models.SessionInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("LastModifiedOn");

                    b.Property<int>("MessId");

                    b.Property<DateTime>("SessionEnd");

                    b.Property<DateTime>("SessionStart");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("MessDotCity.API.Models.UnreadNotice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MemberId");

                    b.Property<int>("NoticeId");

                    b.HasKey("Id");

                    b.ToTable("UnreadNotices");
                });

            modelBuilder.Entity("MessDotCity.API.Models.UserInfo", b =>
                {
                    b.Property<string>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<bool>("IsEmailVerified");

                    b.Property<bool>("IsMobileVerified");

                    b.Property<string>("LastName");

                    b.Property<string>("Mobile");

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt");

                    b.Property<string>("PhotoUrl");

                    b.Property<string>("Profession");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MessDotCity.API.Models.Request", b =>
                {
                    b.HasOne("MessDotCity.API.Models.UserInfo", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
